### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by ghost** [ColeHud/InstaGrub#3]
Is this project dead or alive, because I sure do like the idea and would like to see it finished.

**Comment by ColeHud** [comment]
No, it's definitely not dead. These last few weeks have been pretty rough. I had to make one of the biggest decisions of my life, so I spent a lot of time just talking with my parents. I also had to study for the AP Computer Science exam, so I was pretty busy. Expect some upcoming development :)

**Comment by ghost** [comment]
GR8, I'd love to contribute a little bit.

**Comment by ColeHud** [comment]
Hey, I just finished up school, so I can start working on the project again. Do you have any good ideas for a back-end? I'm planning on using parse, but I'm not sure how well that would scale

**Comment by ghost** [comment]
Yeah, how about writing it in PHP and hosting it on a digital ocean droplet, that ay when we scale up it can easily be transferred to an AWS.

**Comment by ColeHud** [comment]
I'm not terribly good with PHP. Do you think that Node.js would work as well?

**Comment by ghost** [comment]
Probably, I have 0 experience with node.js. Does it easily let you make changes to SQL databases?

**Comment by ColeHud** [comment]
I'll check. I have a bit of experience with it, but I"m learning a lot more

**Comment by ColeHud** [comment]
I just checked, and it works nicely with sqlite

**Comment by ghost** [comment]
That's great. PHP is a really great language.

**Comment by ghost** [comment]
Oh, um, do you know SQLite?

**Comment by ColeHud** [comment]
:) I'm still learning

**Comment by ColeHud** [comment]
https://www.npmjs.com/package/sqlite3

**Comment by ghost** [comment]
Oh, that's gr8

**Comment by ghost** [comment]
What port should we use?

**Comment by ColeHud** [comment]
port?

**Comment by ghost** [comment]
Awesome!

**Comment by ghost** [comment]
Yeah when we send data between the user and the server it goes through a port

**Comment by ghost** [comment]
For example if this website wasn't encrypted than it would be port 80

**Comment by ColeHud** [comment]
Ok, I wasn't sure which port you were talking about. I was thinking about maybe 666? :p

**Comment by ghost** [comment]
Um, maybe. Lol

**Comment by ColeHud** [comment]
Ok, I've got to go. Thanks for all of the help. I'll talk to you later

**Comment by ghost** [comment]
http://en.m.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

Observe how all these programs use a port

**Comment by ColeHud** [comment]
Hey, Love2code, ummmm, so I accidentally forgot to make my awesomechat repo private. Would you mind deleting that app?

**Comment by ColeHud** [comment]
My neighbors can't get any kind of social media, so I designed this app so my siblings, neighbors and I can message

**Comment by ColeHud** [comment]
Also, could you send me a link to your facebook profile so that I can add you? I find it much easier to chat with facebook messenger than with github

**Comment by ghost** [comment]
no

**Comment by ghost** [comment]
and the app = deleted

**Comment by ColeHud** [comment]
Thanks

**Comment by ghost** [comment]
Anyway.....

**Comment by ghost** [comment]
Are you going to make an organisation for the app or something. Or do you want to just, keeping accepting those pull requests.

**Comment by ColeHud** [comment]
pull requests
